linux-next: build failure after merge of the net-next tree
Hi all,

After merging the net-next tree, today's linux-next build (x86_64
allmodconfig) failed like this:

drivers/net/phy/aquantia/aquantia_firmware.c: In function 'aqr_fw_load_memory':
drivers/net/phy/aquantia/aquantia_firmware.c:135:23: error: implicit declaration of function 'crc_ccitt_false'; did you mean 'crc_ccitt_byte'? [-Werror=implicit-function-declaration]
  135 |                 crc = crc_ccitt_false(crc, crc_data, sizeof(crc_data));
      |                       ^~~~~~~~~~~~~~~
      |                       crc_ccitt_byte

Caused by commit

  e93984ebc1c8 ("net: phy: aquantia: add firmware load support")

interacting with commit

  56ded2dd1a43 ("lib: crc_ccitt_false() is identical to crc_itu_t()")

from the mm tree.

I have applied the following merge fix patch:

From: Stephen Rothwell <sfr@canb.auug.org.au>
Date: Thu, 21 Dec 2023 12:49:11 +1100
Subject: [PATCH] fix up for "net: phy: aquantia: add firmware load support"

interacting with commit

  56ded2dd1a43 ("lib: crc_ccitt_false() is identical to crc_itu_t()")

from the mm tree.

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>